### ISSUE TITLE
Location is not showing step4_solution

### ISSUE THREAD

**Issue by ideepdave** [googlecodelabs/android-lifecycles#39] opened 2018-06-20 14:08 UTC
Lat Long is not showing up..
Tried including three lines as mentioned in codelabs , step 4.
Failed to achieve desired output
Running Solution_step4 is also resulting same textview saying 'Location'
Devices tested on : Samsung SM-G610F 7.0 24 & Redmi Note 5
Let me know what i am doing wrong.

**Comment by ceruleanotter** [comment] 2019-11-08 01:04
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. This codelab has been tested on a Pixel emulator (and is producing a location); any issue getting location is outside the scope of lifecycle unfortunately.

If you think that this is a problem of one of the Architecture Component libraries, please open a bug on the public issue tracker. Instructions for doing so are [here](https://developer.android.com/jetpack/docs/feedback#issues)

**Closed by ceruleanotter** 2019-11-08 01:04 UTC
