### ISSUE TITLE
Next Button Not Working

### ISSUE THREAD

**Issue by bhargavasatyamani** [googlecodelabs/android-lifecycles#46] opened 2018-10-24 06:11 UTC
Unable to navigate to other steps after introduction. Even direct link isnt working

**Comment by ceruleanotter** [comment] 2019-11-08 07:11
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. If you are referring to the blue "next" button in the actual codelab, this should work. Please let me know what browser and page you are on.

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.

**Closed by ceruleanotter** 2019-11-08 07:11 UTC
