### ISSUE TITLE
ChronoActivity2 Does Not Exist

### ISSUE THREAD

**Issue by labermt** [googlecodelabs/android-lifecycles#60] opened 2019-05-29 23:50 UTC
Unable clone, don't have permissions. Downloaded .zip, ChronoActivity2 does not exist as indicated in Step 2.

**Comment by morteryler** [comment] 2019-07-27 16:38
update you idea program

**Comment by hakimrie** [comment] 2019-09-04 12:24
make sure to follow this codelabs https://codelabs.developers.google.com/codelabs/android-lifecycles/index.html?index=..%2F..index#3

there is a step to copy configuration to make it work

**Comment by ceruleanotter** [comment] 2019-11-08 07:46
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. I believe this is an issue, as @hakimrie mentioned, of missing a step in [Setup your Environment](https://codelabs.developers.google.com/codelabs/android-lifecycles/#1), which adds the appropriate run configurations. I've tried to make this clearer in the codelab text and will republish.

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.

**Closed by ceruleanotter** 2019-11-08 07:46 UTC
