### ISSUE TITLE
Run Configurations missing

### ISSUE THREAD

**Issue by rscovilCP** [googlecodelabs/android-lifecycles#44] opened 2018-10-20 21:44 UTC
Can't select run configurations during tutorial.  While the repo shows .idea/runConfigurations with 8 configuration files, the master download does not have this folder.  ..idea/ does have a runConfigurations.xml that doesn't list the steps.

**Comment by ceruleanotter** [comment] 2019-11-08 07:10
Thanks for reporting this and the feedback!

I'm closing this issue because I cannot reproduce it in this codelab. I believe this issue has been resolved - the codelab currently contains instructions for Windows/Mac for setting up the proper runtime configurations: https://codelabs.developers.google.com/codelabs/android-lifecycles/#1

If you still think this is an issue with the codelab, please re-open this issue and let me know whether you were cloning/downloading from zip and what version of Android Studio you're on.

**Closed by ceruleanotter** 2019-11-08 07:10 UTC
